version: "3.5"

services:
  renewx:
    image: zilanlann/ms365_e5_renewx:latest
    container_name: renewx
    #    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - LoginPassword=<your login password>
    volumes:
      - renewx-deploy:/renewx/Deploy/
      - renewx-appdata:/renewx/appdata/
    ports:
      - "1066:1066"
    restart: unless-stopped

volumes:
  renewx-deploy:
  renewx-appdata:
